"""add_openai_api_base_to_system_configuration

Revision ID: 2c16fa5d2920
Revises: 5e4e8911036d
Create Date: 2025-05-18 14:49:55.512207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c16fa5d2920'
down_revision: Union[str, None] = '5e4e8911036d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configuration', sa.Column('openai_api_base', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configuration', 'openai_api_base')
    # ### end Alembic commands ###
