"""add_storm_progress_updates_table

Revision ID: 6c0e38575b57
Revises: e906c65d2213
Create Date: 2025-06-04 09:29:08.794012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0e38575b57'
down_revision: Union[str, None] = 'e906c65d2213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storm_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='stormrunstatus'), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_dir', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storm_runs_id'), 'storm_runs', ['id'], unique=False)
    op.create_index(op.f('ix_storm_runs_topic'), 'storm_runs', ['topic'], unique=False)
    op.create_table('system_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('small_model_name', sa.String(), nullable=True),
    sa.Column('large_model_name', sa.String(), nullable=True),
    sa.Column('small_model_name_azure', sa.String(), nullable=True),
    sa.Column('large_model_name_azure', sa.String(), nullable=True),
    sa.Column('azure_api_base', sa.String(), nullable=True),
    sa.Column('openai_api_base', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=True),
    sa.Column('openai_api_type', sa.String(), nullable=True),
    sa.Column('azure_api_version', sa.String(), nullable=True),
    sa.Column('tavily_api_key', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('storm_progress_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['storm_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storm_progress_updates_id'), 'storm_progress_updates', ['id'], unique=False)
    op.create_index(op.f('ix_storm_progress_updates_run_id'), 'storm_progress_updates', ['run_id'], unique=False)
    op.create_index(op.f('ix_storm_progress_updates_timestamp'), 'storm_progress_updates', ['timestamp'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('max_runs', sa.Integer(), nullable=False),
    sa.Column('used_runs', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=True)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_storm_progress_updates_timestamp'), table_name='storm_progress_updates')
    op.drop_index(op.f('ix_storm_progress_updates_run_id'), table_name='storm_progress_updates')
    op.drop_index(op.f('ix_storm_progress_updates_id'), table_name='storm_progress_updates')
    op.drop_table('storm_progress_updates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_storm_runs_topic'), table_name='storm_runs')
    op.drop_index(op.f('ix_storm_runs_id'), table_name='storm_runs')
    op.drop_table('storm_runs')
    # ### end Alembic commands ###
