"""add_api_keys_and_type_to_system_config

Revision ID: e906c65d2213
Revises: 2c16fa5d2920
Create Date: 2025-05-18 19:59:56.137506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e906c65d2213'
down_revision: Union[str, None] = '2c16fa5d2920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configuration', sa.Column('openai_api_key', sa.String(), nullable=True))
    op.add_column('system_configuration', sa.Column('openai_api_type', sa.String(), nullable=True))
    op.add_column('system_configuration', sa.Column('azure_api_version', sa.String(), nullable=True))
    op.add_column('system_configuration', sa.Column('tavily_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configuration', 'tavily_api_key')
    op.drop_column('system_configuration', 'azure_api_version')
    op.drop_column('system_configuration', 'openai_api_type')
    op.drop_column('system_configuration', 'openai_api_key')
    # ### end Alembic commands ###
